import { NextRequest, NextResponse } from 'next/server'

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * - article/
     * - topic/
     * - author/
     * - tag/
     * - category/
     * - all/
     * - assets/
     */
    '/((?!_next/static|_next/image|favicon.ico|article/|topic/|author/|tag/|category/|all/|assets/).*)',
  ],
}

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl
  console.log('pathname in the middleware:', pathname)

  if (oldArticleSlugs.indexOf(pathname) > -1) {
    return NextResponse.redirect(
      new URL(`https://kids.twreporter.org/article${pathname}`, request.url)
    )
  }
}

const oldArticleSlugs = [
  '/body-boundary-and-sexual-violence-reading-material',
  '/e-cigarette-myth-test',
  '/knowledge-how-to-take-antibiotic-medicine',
  '/roep-carnivorous-plants-vertical-wetland',
  '/roep-disney-princess-female-image',
  '/kids-reporter-kinmen-city-god-reception-parade',
  '/knowledge-tobacco-marketing',
  '/climate-change-green-building',
  '/health-and-physical-tobacco-control-education-teacher',
  '/roep-teaching-experience-sharing',
  '/fight-for-democracy-game-parent-child-conversation',
  '/islam-muslim-children-picture-books',
  '/student-model-members-of-the-legislative-yuan-election',
  '/what-is-a-goblin-english',
  '/my-14-year-old-self-cheng-tsung-lung',
  '/climate-change-the-hottest-july',
  '/kids-and-covid-19-omicron-medical-laboratory-scientist',
  '/roep-climbing-security',
  '/what-is-a-goblin',
  '/submission-scores-mean-nothing',
  '/royalty-rank-british',
  '/japan-elementary-school-student-council',
  '/roep-sunburn-protection-and-eco-friendly',
  '/artemis-first-woman-walk-on-the-moon',
  '/climate-change-infographic',
  '/podcast-howard-space-race',
  '/hpv-vaccine-and-junior-high-school-boy',
  '/ming-dean-cheng-climate-change',
  '/islam-muslim-culture-test',
  '/islamophobia',
  '/kids-reporter-kinmen-pa-hua-chao-wang-cheng-jinq',
  '/kids-magazine-1-jillyang',
  '/podcast-drug-safety',
  '/knowledge-cbs-earthquake-alerts',
  '/opinion-china-a4-revolution',
  '/elementary-school-little-mayor',
  '/knowledge-seedless-watermelon-birth-control',
  '/amendment-of-tobacco-hazards-prevention-act',
  '/my-14-year-old-self-chien-ming-wang',
  '/podcast-chuckchu-reading-literacy',
  '/hpv-vaccine-injuredgirls',
  '/international-law-doesnt-protect-people-fleeing-environmental-disaster-heres-how-it-could',
  '/roep-learning-portfolio-pros-and-cons',
  '/school-pokemon-animal-rocket-raccoon',
  '/school-pokemon-animal-shiba-inu-li-ke-le',
  '/russian-invasion-of-ukraine-2022-kid-reflection',
  '/e-cigarette-graphic-story',
  '/climate-change-evolution-of-the-air-conditioner',
  '/generative-ai-is-forcing-people-to-rethink-what-it-means-to-be-authentic-english',
  '/aerospace-rocket-scientist-chong-sin-wu',
  '/china-a4-revolution-young-protesters',
  '/china-a4-revolution-six-keywords',
  '/taiwan-higher-education-children-question',
  '/china-a4-revolution-knock-on-effect-observations',
  '/kids-reporter-kinmen-tian-zhen-tang-lion-dance-troupe',
  '/mothers-day-picture-books',
  '/russian-invasion-of-ukraine-2022-kid-photos',
  '/school-pokemon-animal-leopard-gecko',
  '/knowledge-taiwan-mangoes',
  '/podcast-jinding-elementary-school',
  '/kids-reporter-kinmen-jinding-elementary-school-students-and-teachers-thoughts',
  '/kids-and-covid-19-omicron-self-evaluation-of-vaccination',
  '/russian-invasion-of-ukraine-2022-kid-reading-materials',
  '/taiwan-pirls-2021',
  '/knowledge-space-taiwan-distance-karman-line',
  '/generative-ai-is-forcing-people-to-rethink-what-it-means-to-be-authentic',
  '/kids-and-covid-19-omicron-evolution',
  '/knowledge-early-warning-signals-in-plant',
  '/emergency-overstrain-2022-situation',
  '/artemis-nasa-america-go-back-to-the-moon',
  '/knowledge-naegleria-fowleri',
  '/opinion-new-zealand-smokefree-2025',
  '/hpv-vaccine-injuredgirls-graphic-story',
  '/islam-muslim-ramadan-taiwan-restaurant',
  '/hpv-vaccine-children-question',
  '/kids-magazine-1-mlchen',
  '/russian-invasion-of-ukraine-2022-kid-my-ukrainian-friend',
  '/japanese-yen-history-observation',
  '/kids-magazine-1-jbhuang',
  '/roep-emotion-management',
  '/submission-my-depressed-mom-happiness',
  '/roep-cooling-blanket',
  '/russian-invasion-of-ukraine-2022-kid-fixer',
  '/emergency-overstrain-2022-keywords',
  '/kids-reporter-kinmen-jinding-elementary-school-teacher-view',
  '/kids-magazine-1-yichanlin',
  '/russian-invasion-of-ukraine-2022-kid-six-keywords',
  '/japan-covid-19-taiwanese-bubble-tea-startup',
  '/roep-aging-society-effects',
  '/knowledge-covid-19-omicron-animal-infection',
  '/royalty-paparazzi',
  '/royalty-picture-books',
  '/japanese-yen-depreciation-policy',
  '/my-14-year-old-self-lin-mei-ling',
  '/japanese-yen-depreciation-game',
  '/islam-muslim-ramadan-menstruating-women-soldiers-athletes',
  '/climate-change-india-air-conditioner',
  '/lesson-plan-space',
  '/lesson-plan-climate-change',
  '/hospital-picture-books',
  '/moon-landing-astronaut',
  '/russian-invasion-of-ukraine-2022-graphic-story',
  '/student-government-president',
  '/roep-vtuber-effects',
  '/lesson-plan-e-cigarette',
  '/royalty-hrh-prince-charles-prince-of-wales-british',
  '/royalty-politics-and-culture-quiz',
  '/royalty-the-queens-platinum-jubilee-british',
  '/addiction-picture-books',
  '/climate-change-picture-books',
  '/roep-junk-food',
  '/international-law-doesnt-protect-people-fleeing-environmental-disaster-heres-how-it-could-english',
  '/what-are-hela-cells-a-cancer-biologist-explains-english',
  '/plain-law-movement-metoo-and-body-boundary',
  '/russian-invasion-of-ukraine-2022-kid-quiz',
  '/experimental-school-council',
  '/roep-edible-insects-future-food',
  '/what-are-hela-cells-a-cancer-biologist-explains',
  '/russian-invasion-of-ukraine-2022-kid-russian-and-ukrainian-picture-books',
  '/how-to-talk-to-children-about-the-russian-invasion-of-ukraine',
  '/taiwan-higher-education-ntu-survey',
  '/beyond-spy-balloons-here-are-7-kinds-of-intelligence-spies-want-and-how-they-get-it-english',
  '/school-pokemon-animal-goat',
  '/space-rocket',
  '/japanese-yen-depreciation-situation',
  '/beyond-spy-balloons-here-are-7-kinds-of-intelligence-spies-want-and-how-they-get-it',
  '/metoo-on-tiktok-teens-use-viral-trend-to-speak-out-about-their-sexual-harassment-experiences-english',
  '/emergency-overstrain-2022-game',
  '/islam-muslim-ramadan-tradition',
  '/kids-and-covid-19-omicron-confirmed-case',
  '/how-to-talk-to-children-about-the-russian-invasion-of-ukraine-english',
  '/university-exploratory-learning-zoo',
  '/lesson-plan-muslim-ramadan',
  '/taiwan-higher-education-parent-child-conversation',
  '/podcast-catherine-lu-russian-invasion-of-ukraine',
  '/podcast-israel-gaza-war',
  '/china-covid-19-grid-management',
  '/china-a4-revolution-parent-child-conversation',
  '/what-is-hpv-and-how-to-prevent',
  '/japan-kyoto-covid-19-tourism-industry',
  '/emergency-overstrain-2022-head-nurse',
  '/school-pokemon-animal-african-spurred-tortoise',
  '/china-a4-revolution-lennon-wall',
  '/russian-invasion-of-ukraine-2022-kid-frequently-asked-questions',
  '/arrc-rocket-flight-test-at-syuhai',
  '/china-lunar-exploration-project',
  '/metoo-body-boundary-law',
  '/knowledge-space-crime',
  '/kids-sunflowers-we-stand-with-ukraine',
  '/e-cigarette-tobacco-hazard-infographic',
  '/russian-invasion-of-ukraine-2022-kid-how-can-we-help-ukraine',
  '/metoo-on-tiktok-teens-use-viral-trend-to-speak-out-about-their-sexual-harassment-experiences',
  '/taiwan-higher-education-statistic',
  '/roep-vietnamese-immigrant-get-ued-to-life-in-taiwan',
  '/submission-my-tao-indigenous-dad-and-depressed-mom',
  '/elementary-school-and-junior-high-school-council',
  '/taiwan-higher-education-high-academic-achievement-students-psychological-distress',
  '/taiwan-earthquake-escape-game',
  '/islam-muslim-ramadan-diet-and-health',
  '/podcast-mindi-islam-muslim',
  '/kids-magazine-1-donate',
]
